website/Models/Rates/RateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Milton.Website.Models.Rates
{
    public class RateViewModel
    {
        public int HospitalId { get; set; }
        public string Name { get; set; }
        public decimal? BostwanaPrice { get; set; }
        public decimal? BotswanaReturnPrice { get; set; }
        public decimal? SwazilandPrice { get; set; }
        public decimal? SwazilandReturnPrice { get; set; }
    }
}

website/Controllers/Rates/RatesController.cs
using Milton.Services.Medical;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Milton.Website.Controllers.Rates
{
    public partial class RatesController : BaseController
    {
        #region Fields

        protected IHospitalService _hospitalService;

        #endregion

        #region Constructor

        public RatesController(IHospitalService hospitalService)
        {
            _hospitalService = hospitalService;
        }

        #endregion
    }
}

website/Views/Rates/Index.cshtml
<section class="page-header alternative-header">
    <ol class="breadcrumb">
        <li>Milton</li>
        <li>Patients</li>
    </ol>
    <div class="page-header_title">
        <h1>
            Patients
            <span class="page-header_subtitle"></span>
        </h1>
    </div>
</section>

<section class="page-content">

    <div class="col-lg-12">
        <h4>Hospitals:</h4>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="panel-table-inner-offset">
                    <table id="hospitals" class="table dataTable no-footer" role="grid" aria-describedby="tableDataTables1_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="tableDataTables1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Patient Firstnames">Name</th>
                                <th class="sorting" tabindex="0" aria-controls="tableDataTables1" rowspan="1" colspan="1" aria-label="Botswana Price">Botswana Price</th>
                                <th class="sorting" tabindex="0" aria-controls="tableDataTables1" rowspan="1" colspan="1" aria-label="Botswana Return Price">Botswana Return Price</th>
                                <th class="sorting" tabindex="0" aria-controls="tableDataTables1" rowspan="1" colspan="1" aria-label="Swaziland Price">Swaziland Price</th>
                                <th class="sorting" tabindex="0" aria-controls="tableDataTables1" rowspan="1" colspan="1" aria-label="Swaziland Return Price">Swaziland Return Price</th>
                                <th class="sorting" tabindex="0" aria-controls="tableDataTables1" rowspan="1" colspan="1" aria-label="Actions">Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

</section>

@section Scripts{

    <script>

        $(function () {

            $('#hospitals').dataTable({
                serverSide: true,
                processing: true,
                ajaxSource: '/rates/Json',
                columns: [
                    {
                        data: 'Name',
                        sortable: false,
                        searchable: false,
                        width: '25%'
                    },
                    {
                        data: 'BotswanaPrice',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'BotswanaReturnPrice',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'SwazilandPrice',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'SwazilandReturnPrice',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: null,
                        sortable: false,
                        searchable: false,
                        render: function (data, type, full, meta) {
                            return '<a class="btn btn-info btn-xs" href="/rates/manage?hospitalId=' + data.HospitalId + '"><i class="fa fa-pencil"></i></a>';
                        }
                    }
                ]
            });

        });

    </script>

}

website/Views/Rates/Manage.cshtml
@model Milton.Website.Models.Rates.RateViewModel
<section class="page-header alternative-header">
    <ol class="breadcrumb">
        <li>Milton</li>
        <li>Rates</li>
        <li>Manage</li>
    </ol>
    <div class="page-header_title">
        <h1>
            Manage Hospital Rates (@Model)
            <span class="page-header_subtitle"></span>
        </h1>
    </div>
</section>

<section class="page-content">

    <div class="panel panel-default">
        <div class="panel-body">
            @using (Html.BeginForm("Manage", "Rates", FormMethod.Post, new { id = "rates-form", @class = "form", role = "form" }))
            {
                @Html.HiddenFor(m => m.HospitalId)
                <div class="form-group">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    <label for="Name">Name</label>
                </div>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.BostwanaPrice, new { @class = "form-control" })
                    <label for="BostwanaPrice">Botswana Price</label>
                </div>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.BotswanaReturnPrice, new { @class = "form-control" })
                    <label for="BotswanaReturnPrice">Botswana Return Price</label>
                </div>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.SwazilandPrice, new { @class = "form-control" })
                    <label for="SwazilandPrice">Swaziland Price</label>
                </div>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.SwazilandReturnPrice, new { @class = "form-control" })
                    <label for="SwazilandReturnPrice">Swaziland Return Price</label>
                </div>
                <div class="form-group text-right">
                    <button type="submit" class="btn btn-primary materialRipple-light materialRipple-btn">Save<div class="materialRipple-md-ripple-container"></div></button>
                    <a href="/rates" class="btn btn-danger materialRipple-light materialRipple-btn">Cancel<div class="materialRipple-md-ripple-container"></div></a>
                </div>
            }
        </div>
    </div>

</section>

@section Scripts{

    <script>

        $(document).ready(function () {
            $('#rates-form').validate({
                rules: {
                    Name: {
                        required: true
                    },
                    BotswanaPrice: {
                        required: true
                    },
                    BotswanaReturnPrice: {
                        required: true
                    },
                    SwazilandPrice: {
                        required: true
                    },
                    SwazilandReturnPrice: {
                        required: true
                    }
                },
                highlight: function (element) {
                    $(element).closest('.form-group').addClass('has-error');
                },
                unhighlight: function (element) {
                    $(element).closest('.form-group').removeClass('has-error');
                },
                errorElement: 'span',
                errorClass: 'help-block',
                errorPlacement: function (error, element) {
                    if (element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
        });

    </script>

}